---
deployment:
  tasks:
    - "echo 'Pre up files...'"
    # - /usr/local/cpanel/3rdparty/bin/git commit -m "changes in pro"
metadata:
    name: "App Qr"
    version: "1.0"
    author: "Danilo Grisalez"
post_deploy:
pre_deploy:
    - "echo 'Pre up files...'"
hooks:
  pre:
    - command: "echo 'Backing up files...'"
  post:
    - command: "echo 'Deployment complete.'"